allowBuilds:
  '@parcel/watcher': set this to true or false
  es5-ext: false
  esbuild: true
#injectWorkspacePackages: true
# Denne trengs for bygging av Docker-image, men vi bør kanskje finne en annen løsning
#forceLegacyDeploy: true

packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^19.2.7"
  react-dom: "^19.2.7"
  "@types/react": "^19.2.17"
  "@types/react-dom": "^19.2.3"
  "@navikt/ds-react": "^8.12.1"
  "@navikt/ds-css": "^8.12.1"
  "@navikt/aksel-icons": "^8.13.1"
  "@tanstack/react-query": "^5.101.0"
  "react-router": "^8.0.0"
  "@react-router/node": "^8.0.0"
  "@react-router/serve": "^8.0.0"
  "@react-router/dev": "^8.0.0"
  "@tailwindcss/vite": "^4.3.1"
  "tailwindcss": "^4.3.1"
