export default {
    brukerveildning: {
        tabell_skattepliktig: "tabell-skattepliktig",
        tabell_småbarnstillegg: "tabell-smaabarnstillegg",
        tabell_utvidetbarnetrygd: "tabell-utvidetbarnetrygd",
        tabell_barnetillegg: "tabell-barnetillegg",
        tabell_kontantstøtte: "tabell-kontantstotte",
        tabell_totalt: "tabell-totalt",
        tittel_virkningstidspunkt: "virkningstidspunkt",
        tittel_utgift: "utgift",
        tittel_boforhold: "boforhold",
        tittel_underholdskostnad: "underholdskostnad",
        tittel_privat_avtale: "privat-avtale",
        tittel_inntekt: "inntekt-generelt",
        tittel_klagevedtak: "klagevedtak",
        tittel_vedtak: "fatte-vedtak",
        tittel_samvær: "samvær",
        tittel_gebyr: "gebyr",
    },
    seksjon_andreVoksneIHusstand: "andre_voksne_i_husstand",
    seksjon_boforhold: "boforhold",
    seksjon_inntekt_barnetillegg: "barnetillegg",
    seksjon_inntekt_kontantstøtte: "kontantstotte",
    seksjon_inntekt_skattepliktig: "skattepliktig",
    seksjon_inntekt_småbarnstillegg: "smaabarnstillegg",
    seksjon_inntekt_utvidetbarnetrygd: "utvidetbarnetrygd",
    seksjon_offentlige_opplysninger: "offentlige_opplysninger",
    seksjon_perioder: "perioder",
    seksjon_sivilstand: "sivilstand",
    seksjon_samvær: "samvær",
    seksjon_virkningstidspunkt: "virkningstidspunkt",
    seksjon_gebyr: "gebyr",
    seksjon_underholdskostnader: "underholdskostnader",
    seksjon_underholdskostnad_barnetilsyn: "barnetilsyn",
    seksjon_underholdskostnad_beregnet: "underholdskostnad_beregnet",
    seksjon_underholdskostnad_tilysnsutgifter: "tilysnsutgifter",
    seksjon_underholdskostnad_tilleggstønad: "tilleggstønad",
};
