export const INNTEKT_BEGRUNNELSE_MAL_BIDRAG = [
    "<h4>Hva er partens faktisk inntekt</h4>",
    "<p><br/></p>",
    "<h4>Hvilken inntekt bør parten kunne oppnå utfra evne?</h4>",
    "<p><br/></p>",
    "<h4>Er faktisk inntekt vesentlig lavere enn inntektsevnen?</h4>",
    "<p><br/></p>",
    "<h4>Har parten rimelig grunn for dette?</h4>",
    "<p><br/></p>",
    "<h4>Skal inntekten fastsettes utfra skjønn?</h4>",
    "<p><br/></p>",
    "<h4>Inntekt som legges til grunn m/hjemmel for grunnlag:</h4>",
    "<p><br/></p>",
    "<h4>Skal inntekten til totrinnskontroll?</h4>",
    "<p><br/></p>",
    "<h4>Totrinn kontrollør sin signatur m/dato</h4>",
    "<p><br/></p>",
].join("");
export const INNTEKT_BEGRUNNELSE_MAL_BM_BIDRAG = [
    "<h4>Hva er partens faktisk inntekt</h4>",
    "<p><br/></p>",
    "<h4>Hvilken inntekt bør parten kunne oppnå utfra evne?</h4>",
    "<p><br/></p>",
    "<h4>Er faktisk inntekt vesentlig lavere enn inntektsevnen?</h4>",
    "<p><br/></p>",
    "<h4>Har parten rimelig grunn for dette?</h4>",
    "<p><br/></p>",
    "<h4>Skal inntekten fastsettes utfra skjønn?</h4>",
    "<p><br/></p>",
    "<h4>Inntekt som legges til grunn m/hjemmel for grunnlag:</h4>",
    "<p><br/></p>",
    "<h4>Skal inntekten til totrinnskontroll?</h4>",
    "<p><br/></p>",
    "<h4>Totrinn kontrollør sin signatur m/dato</h4>",
    "<p><br/></p>",
    "<h4>Er forskuddet riktig?</h4>",
    "<p><br/></p>",
].join("");
export const INNTEKT_BEGRUNNELSE_MAL_SÆRBIDRAG = [
    "<h4>Hva er partens faktisk inntekt</h4>",
    "<p><br/></p>",
    "<h4>Hvilken inntekt bør parten kunne oppnå utfra evne?</h4>",
    "<p><br/></p>",
    "<h4>Er faktisk inntekt vesentlig lavere enn inntektsevnen?</h4>",
    "<p><br/></p>",
    "<h4>Har parten rimelig grunn for dette?</h4>",
    "<p><br/></p>",
    "<h4>Skal inntekten fastsettes utfra skjønn?</h4>",
    "<p><br/></p>",
    "<h4>Inntekt som legges til grunn m/hjemmel for grunnlag:</h4>",
    "<p><br/></p>",
    "<h4>Skal inntekten til totrinnskontroll?</h4>",
    "<p><br/></p>",
    "<h4>Totrinn kontrollør sin signatur m/dato</h4>",
    "<p><br/></p>",
].join("");
