export {
    BEHANDLING_API_V1,
    BIDRAG_DOKUMENT_PRODUKSJON_API,
    BIDRAG_ORGANISASJON_API as ORGANISASJON_API,
    BIDRAG_PERSON_API as PERSON_API,
    BIDRAG_SAK_API as SAK_API,
    BIDRAG_VEDTAK_API as VEDTAK_API,
} from "@bidrag/api";
