name: Build reusable workflow
on:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true
        description: 'Token with read access to the repository'
    inputs:
      docker:
        description: 'Build Docker image'
        required: false
        default: true
        type: boolean
    outputs:
      image:
        description: 'Docker image'
        value: ${{ jobs.bygg.outputs.image }}
      telemetry:
        description: 'Telemetry data'
        value: ${{ jobs.bygg.outputs.telemetry }}

jobs:
  bygg:
    name: "Test, bygg og push Docker-image"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-auth-token: ${{ secrets.READER_TOKEN }}

      - name: Test
        run: pnpm run test

      - name: Bygg applikasjon
        run: pnpm run build

      - name: Bygg Bygg deploybar applikasjon for Docker
        run: pnpm run deploy:docker

      - name: Push Docker-image til GAR
        if: ${{ inputs.docker }}
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: bidrag
