name: "Pipeline for main"
on:
  push:
    branches: [ main ]

jobs:
  test:
    name: "Test og valider"
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write

  deploy:
    needs: test
    name: "Start utrulling"
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write