name: Bygg og test på branch
on:
  pull_request:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
