name: Deploy til q1
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write

  deploy_q1:
    needs:
      - build
    name: "Deploy til q1"
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - name: Deploy til dev-gcp q1
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          ENVIRONMENT: q1
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/q1.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
